### ISSUE TITLE
Many components - The tab "API" doesn't display any information

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1706]
**Describe the bug**

The tab API doesn't display any information, it's blank, for many components, this is the full list:

- [x] badge
- [x] badge counter
- [x] drawer
- [x] modal
- [x] pin input
- [x] tabs
- [x] tooltip
- [x] validation code

**Steps to reproduce**

1. Go to https://sui-components.vercel.app/workbench/atom/badge/demo
2. Click on the API Tab
3. See error

**Expected behaviour**

This Tab should display info, as you can see in [this one](https://sui-components.vercel.app/workbench/atom/button/documentation/api)

**Screenshots**

![broken API](https://user-images.githubusercontent.com/23620759/135096964-f9238d75-f019-46ec-9101-abbeb231635f.png)

**Environment / Context**

- The components are ok, it's just the Tab

**Additional info**
-

**Comment by andresin87** [comment]
[x] Autocomplete
[x] Select
