### ISSUE TITLE
Remove spacing by applying the new Prop 'isFitted'

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1708]
**Is your iteration request related to a problem?**
According to our agreements, our components will only manage the spacing within themselves.
No padding or margin should be applied to control how the component behaves in relation to its context.

i.e.:
1. A button next to another button should have no space in between
2. A breadcrumb shouldn't have any margin around
3. etc

**Describe the solution you'd like**
As discussed in [this discussion](https://github.com/SUI-Components/sui-components/discussions/1667) we've agreed to create a new prop "isFitted" in all the components that are currently breaking this agreement.

This new prop removes the unwanted spacing, although it must be set to "false" by default.

**Affected components**

- [x] [badge](https://sui-components.vercel.app/workbench/atom/badge/demo)
- [x] [button](https://sui-components.vercel.app/workbench/atom/button/demo)
- [ ] [input](https://sui-components.vercel.app/workbench/atom/input/demo)
- [x] [switch](https://sui-components.vercel.app/workbench/atom/switch/demo)
- [x] [tag](https://sui-components.vercel.app/workbench/atom/tag/demo) #1853
- [ ] [breadcrumb](https://sui-components.vercel.app/workbench/molecule/breadcrumb/demo)

**Comment by manudefrutosvila** [comment]
I'll try to do this 😊

**Comment by andresin87** [comment]
@manudefrutosvila will u get another bugged component like button, input, breadcrumb¿?

**Comment by manudefrutosvila** [comment]
Yup I'll try the others!!
Do you prefer one PR each one? Like I did with the tag?

**Comment by andresin87** [comment]
I personally prefer 1 PR per component

**Comment by manudefrutosvila** [comment]
About breadcrumb, I'm not sure if this issue applies!
The breadcrumb nav wrapper is fine
![image](https://user-images.githubusercontent.com/5516760/139447714-e1329708-a423-4289-aab0-7bf74dc088b4.png)
The div inside with class `sui-BreadcrumbBasic` has a padding, is this one which needs isFitted ? or it is ok?
![image](https://user-images.githubusercontent.com/5516760/139448188-e8d02ab7-a64c-434b-aee1-4eff65db8538.png)

**Comment by manudefrutosvila** [comment]
The same situation is with button and input. All three by default does not have outer margin, but inner padding. 

![image](https://user-images.githubusercontent.com/5516760/139450180-3c2a3eb4-876c-4bb8-a9cc-84c3333c0efa.png)

![image](https://user-images.githubusercontent.com/5516760/139450792-83731d69-2f67-492e-8990-d1e571cd4eb8.png)
