### ISSUE TITLE
Checkbox field - Elements alignment

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1733]
Component [checkbox field](https://sui-components.vercel.app/workbench/molecule/checkboxField/demo)

**Is your iteration request related to a problem?**

The alignment of the label, help text and check is not ok

![checkbox wrong](https://user-images.githubusercontent.com/23620759/135394720-cf64671b-8b64-481e-b2f9-c57ac4e18fad.png)

**Describe the solution you'd like**

Horizontal and vertical alignments should be sharp

![checkbox ok](https://user-images.githubusercontent.com/23620759/135394783-60f907d0-8e5d-4888-a3c6-d28942b28b2e.png)

**Additional context**

- It happens in all themes
- Check alignments with custom and native checks
- Alignments are OK in [radio-button fields](https://sui-components.vercel.app/workbench/molecule/radioButtonField/demo)

**Comment by delalama** [comment]
https://github.com/SUI-Components/sui-components/pull/1807
