### ISSUE TITLE
Data counters - The buttons should be squared

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1738]
**Describe the bug**
The buttons are not always 1:1 ratio

![data counter width wrong](https://user-images.githubusercontent.com/23620759/135399433-f79840a7-09ca-4aa3-b7d0-eaef46ff47fe.png)

**Steps to reproduce**
1. Go to ['data counter'](https://sui-components.vercel.app/workbench/molecule/dataCounter/demo)
2. Scroll down to custom icons 
3. See error

**Expected behaviour**
The buttons should be squared

![data counter width correct](https://user-images.githubusercontent.com/23620759/135399454-98f759c2-f327-4ff4-b3db-c1a9e1a41ff7.png)

**Comment by delalama** [comment]
https://github.com/SUI-Components/sui-components/pull/1831

Work done.

I've seen the previous commit once finished.
