### ISSUE TITLE
Data counters - Keep adding numbers on HOLD

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1739]
**Describe the solution you'd like**

It would be nice to add and remove on button hold

https://user-images.githubusercontent.com/23620759/135400118-a62d0cad-e9b1-45c0-950f-ac603e9999d2.mov

**Comment by Alverd04** [comment]
Hi, can i solve this issue please? #hacktoberfest

**Comment by harshndroid** [comment]
@andresin87 can you help me how can i reproduce this issue?

**Comment by harshndroid** [comment]
> @andresin87 can you help me how can i reproduce this issue?

i meant there are few types inside 'dataCounter' like basic, controlled, loading.
So exactly on which type we want this functionality to be added ?
