### ISSUE TITLE
Drawers DEMO - The drawers shouldn't have scrollbars by default

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1741]
**Describe the bug**
All drawers in the demo have a Scrollbar visible even when it's not needed

**Steps to reproduce**
1. Go to [drawers](https://sui-components.vercel.app/workbench/molecule/drawer/demo)
2. See error

**Expected behaviour**
- Scrollbars should not be enabled by default,
- Adjust overflows to "auto"

**Screenshots**
![drawer scrollbar](https://user-images.githubusercontent.com/23620759/135415177-b111cd50-4f5f-448c-9cd7-9ed217f2e96e.png)

**Comment by andresin87** [comment]
already fixed
