### ISSUE TITLE
Dropdown options: The disabled options should have default cursor

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1744]
**Is your iteration request related to a problem?**
The disabled options show a pointer, and have hover effect, even when they are not interactive

![dropdown option wrong](https://user-images.githubusercontent.com/23620759/135422666-828c8658-01f2-4c21-9378-e3b397d1a29a.png)

**Describe the solution you'd like**

- [x] Disabled options should show a default cursor
- [x] Disabled options should maintain the hover effect

![dropdown option right](https://user-images.githubusercontent.com/23620759/136162243-e885ff38-ad37-4b8c-954b-49fbc4de7e09.png)

**Comment by logicalahara** [comment]
Hey @turolopezsanabria, I saw dropdownOption component for an instance

I think that disabled option's background color should have same background color when its hovered currently (gray) so that user gets an idea of disabled options without taking an extra effort

How can I contribute to this issue ?

**Comment by turolopezsanabria** [comment]
Hey @logicalahara 
@SUI-Components agrees with you, it's a good observation.
i've updated the description

You can go ahead and make a PR
- clone
- add your changes
- commit !important: Don't commit manually, please run "npm run co" and follow the steps
- that's it!

thank you!

**Comment by logicalahara** [comment]
![image](https://user-images.githubusercontent.com/17697162/136662955-f7f8d7de-4908-43be-a313-7952e0e3e3cf.png)

@turolopezsanabria while performing 'npm run dev' throwing this error. Will you please trace and provide a solution ?

**Comment by andresin87** [comment]
@logicalahara 
`npm run dev [category]/[component]`

**Comment by logicalahara** [comment]
@andresin87, ran `npm run dev molecule/dropdownList`

threw error: 

![image](https://user-images.githubusercontent.com/17697162/137591663-ccdf6a7e-64cf-49f6-b907-daa3ace0f684.png)

**Comment by andresin87** [comment]
```
$ rm -rf ./node_modules && rm -f package-lock.json && npm install --prefer-online --legacy-peer-deps
$ npm run phoenix
$ npm run dev molecule/dropdownList
```

**Comment by harshndroid** [comment]
@andresin87 can i try this issue?

**Comment by andresin87** [comment]
> @andresin87 can i try this issue?

Of course yes!
