### ISSUE TITLE
Nested Checkboxes Demo

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1754]
The [Nested Checkboxes demo](https://sui-components.vercel.app/workbench/organism/nestedCheckboxes/demo) is not ok

- [ ] Add examples for each of the props in the API Tab
- [ ] Add examples with Native Checkboxes as well
- [ ] The checkboxes should be independent, at this moment checks in the 1st list mark items on the second

https://user-images.githubusercontent.com/23620759/135438524-9a150778-f753-4dcd-a4c2-5754586127a1.mov

**Comment by oriolpuig** [comment]
Hi @turolopezsanabria 👋🏻
I guess we can close that issue, isn't it?

[Here is the current demo](https://sui-components.vercel.app/workbench/organism/nestedCheckboxes/demo)

**Comment by turolopezsanabria** [comment]
yes! true
