### ISSUE TITLE
Skeleton DEMO - Remove items from the examples section

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1761]
**In order to simplify the [Skeleton](https://sui-components.vercel.app/workbench/atom/skeleton/demo) demo, please adjust the following:**

- Add Skeleton to the image placeholder as well
- Make all the Skeletons the same width
- For ALL examples, make a square example of 200px * 200px

https://user-images.githubusercontent.com/23620759/135512158-5351f22c-d839-44cf-aa30-ec45a8ddb899.mov

- Remove 2 of the 3 examples, leave just the one with the toggle to enable and disable the animation

https://user-images.githubusercontent.com/23620759/135511742-1168e8d6-2e3b-4ece-8af3-834086ab1887.mov

**Comment by stefi23** [comment]
Hi @turolopezsanabria,

I've updated the Variant sizes for the demo. 
I'm not sure about the second part even though I see it in the video. Should it look something like this with just one option:


<img width="789" alt="Screenshot 2022-10-01 at 11 03 58" src="https://user-images.githubusercontent.com/30704597/193401967-63eb484c-82c4-4522-8a84-577111ee82d2.png">

<img width="508" alt="Screenshot 2022-10-01 at 11 04 41" src="https://user-images.githubusercontent.com/30704597/193401989-29e17e60-91f5-4672-98e5-2a1336fa287a.png">

Thank you!
