### ISSUE TITLE
pinInput Demo

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1764]
Component [pinInput](https://sui-components.vercel.app/workbench/atom/input/demo)

**Describe the problem**
The inputs width on the card example should not change

**Steps to reproduce**
1. Go to [`pinInput`](https://sui-components.vercel.app/workbench/atom/input/demo)
2. Scroll down to the card example
3. Resize the screen
3. See error

**Expected behaviour**

Remove `isFullWidth` prop from this component in the Demo
![pin Input card](https://user-images.githubusercontent.com/23620759/135566762-fa727a01-5db1-49a6-b88f-626ca1f301e0.png)

**Comment by harshndroid** [comment]
@turolopezsanabriai I would like to work on this issue. Can you assign this to me?

**Comment by harshndroid** [comment]
@andresin87 i have raised a PR #1860 . Kindly review it.

**Comment by andresin87** [comment]
I know. I'll review soon

**Comment by andresin87** [comment]
fixed
