### ISSUE TITLE
Thumbnail - The width of the Caption is too wide

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1768]
Component [Thumbnail](https://sui-components.vercel.app/workbench/molecule/thumbnail/demo)

**Is your iteration request related to a problem?**
The width of the caption is too wide (100% + padding)

![thumbnail wrong](https://user-images.githubusercontent.com/23620759/135649697-3c2f78a2-3ef7-4ae4-8294-59994d16a3ec.png)

**Describe the solution you'd like**
The correct width should not be wider than the image

![thumbnail](https://user-images.githubusercontent.com/23620759/135649705-e9c6f00c-4918-4ea4-b3d5-f0781d6f1d82.png)

**Comment by delalama** [comment]
https://github.com/SUI-Components/sui-components/pull/1808

**Comment by delalama** [comment]
node -> 16.5.0
npm -> 7.14

on npm run dev i receive this:

/home/elaltas/devel/hacktoberfest/sui-components/node_modules/@s-ui/studio/bin/sui-studio-dev.js:38
const [category, component] = componentID.split('/')
                                          ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/home/elaltas/devel/hacktoberfest/sui-components/node_modules/@s-ui/studio/bin/sui-studio-dev.js:38:43)
    
   
How do you actually deploy dev env?
