### ISSUE TITLE
Rating demo - Improve CUSTOM stars

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1773]
Component [Rating](https://sui-components.vercel.app/workbench/molecule/rating/demo)

**Improvement proposal**
The `custom` icons should really look different from the rest of the demo

Use [these zipped SVG stars](https://github.com/SUI-Components/sui-components/files/7269528/custom.stars.zip)

![custom stars wrong](https://user-images.githubusercontent.com/23620759/135672707-be9070b2-31e2-4d4e-a86b-7d86af0dc9ec.png) ![custom stars right](https://user-images.githubusercontent.com/23620759/135672726-531a1ecf-a854-4f61-92b7-d866581d272e.png)

**Comment by DmnChzl** [comment]
Hi 👋
I want to help!
Can you assign this issue to me? 🤔

**Comment by turolopezsanabria** [comment]
> Hi 👋 I want to help! Can you assign this issue to me? 🤔

sure! Thnx

**Comment by turolopezsanabria** [comment]
closed through https://github.com/SUI-Components/sui-components/pull/1791
👏🏼
