### ISSUE TITLE
Autosuggest - Multiple Selection > disabled effect not working 

### ISSUE THREAD

**Issue by stefi23** [SUI-Components/SUIComponents#1792]
Component [Autosuggest](https://sui-components.vercel.app/workbench/molecule/autosuggest/demo)

**Describe the bug**
Multiple Selection > disabled: component is not truly disabled as one can interact with the tags inside by removing them.

**Steps to reproduce**
1. On the Demo page go to Multiple Selection > disabled
2. Click on the X (close button) of any of the tags - this should not be clickable
2. You can click on the X(close button) on the right and everything will be removed -> this should not be clickable

**Expected behavior**
For a disabled component, it should not be possible to interact with its content. In this case, it is possible to remove the tags.

**Screenshots**

![Screen Recording 2021-10-07 at 18 30 23](https://user-images.githubusercontent.com/30704597/136523590-6080d640-02fb-418f-9654-98d450b42f7b.gif)

**Comment by turolopezsanabria** [comment]
thnx for reporting!
