### ISSUE TITLE
Input - Add 2 new sizes (L and XL)

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1796]
Component: [Input](https://sui-components.vercel.app/workbench/atom/input/demo)

**Is your iteration request related to a problem?**
There are no sizes L and XL for the Input, and we need them (see fotocasa.es homepage for instance)

![Input size](https://user-images.githubusercontent.com/23620759/136559268-b8948a6f-59b1-48f1-821b-830a29c42484.png)

**Describe the solution you'd like**
Add 2 more sizes:

- [ ] L = 48px height, font-size L
- [ ] XL = 56px height, font-size L

![Input new sizes](https://user-images.githubusercontent.com/23620759/136561432-2d17b4b3-9866-43c0-9b9b-e4cfc26676c2.png)

**Comment by inovux** [comment]
Hi, could I pick this one up :)?

**Comment by turolopezsanabria** [comment]
sure thing!

> Hi, could I pick this one up :)?

**Comment by inovux** [comment]
@turolopezsanabria This requires changes in the `sui-theme` package as well right? Else this is not going to work? How do you guys usually do this when the issue was created in this repo?

**Comment by turolopezsanabria** [comment]
hey,
I'm not sure if it needs to be adjusted in [SUI Theme](https://github.com/SUI-Components/sui/tree/master/packages/sui-theme) as well.

I'd say it only needs changes within the scope of the component, i.e. sizes props are [here](https://github.com/SUI-Components/sui-components/blob/master/components/atom/input/src/config.js) but maybe I'm wrong.
I'll let @andresin87 to confirm.

If changes are to be made in the other repo, we just mention this issue in the PR to the other repo, merge the other one 1st, and then move ahead with this one.

**Comment by inovux** [comment]
> hey, I'm not sure if it needs to be adjusted in [SUI Theme](https://github.com/SUI-Components/sui/tree/master/packages/sui-theme) as well.
> 
> I'd say it only needs changes within the scope of the component, i.e. sizes props are [here](https://github.com/SUI-Components/sui-components/blob/master/components/atom/input/src/config.js) but maybe I'm wrong. I'll let @andresin87 to confirm.
> 
> If changes are to be made in the other repo, we just mention this issue in the PR to the other repo, merge the other one 1st, and then move ahead with this one.

Yeah I could be wrong, I was just thinking that this part required the new size definitions just like the others have here: https://github.com/SUI-Components/sui-theme/blob/master/src/components/atom/input/_settings.scss#L1-L3 

As you can see it does not have `x` and `xl` sizes.

**Comment by turolopezsanabria** [comment]
Oh yeap u r right 😄
You can PR in that repo too. I'll tag as hacktoberfesraccepted that PR as well

**Comment by inovux** [comment]
Hi there, alright thanks. I am a bit confused on where to add it exactly? Do you guys have some documentations on this?

I saw you have a monorepo as well that includes the `sui-theme` package so not sure how it works currently?

**Comment by andresin87** [comment]
git clone `sui-components/sui` monorepo multipackage

add l and xl sizes

PR it

when it's integrated (merged-deployed-published) (hacktoberfest accepted of course)

git clone sui-components/sui-components monorepo multipackage

install dependencies

watch out you are using the right version of sui-theme (`npm list @s-ui/theme`)

add the tokens to the right place of the sui-components input component

PR it

🎉

**Comment by andresin87** [comment]
merged, sorry @inovux !

**Comment by inovux** [comment]
@andresin87 no worries:) thanks!

**Comment by andresin87** [comment]
r you @inovux going to take it?

**Comment by inovux** [comment]
@andresin87 yeah im on it  :)

**Comment by inovux** [comment]
@andresin87 for some reason I cant run the latest `master` branch `npm start` does not show any page and returns import errors. Any idea what im doing wrong? Am I missing a step apart from `npm install` ?

**Comment by andresin87** [comment]
to start input only, better run dev mode
`npm run dev atom/input`

**Comment by andresin87** [comment]
anyway, i can open it in start mode also

![image](https://user-images.githubusercontent.com/1674036/137957518-d69ff694-ce1d-4baf-a05e-f38612ffa6e2.png)

**Comment by inovux** [comment]
@andresin87 it somehow cant resolve the modules from `@s-ui` for me

**Comment by andresin87** [comment]
done
