### ISSUE TITLE
Input field - Border radius is wrong for add-on version

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#1798]
**Describe the bug**
The border radius for the input version with add-ons is wrong 

**Steps to reproduce**
1. Go to [Input demo](https://sui-components.vercel.app/workbench/atom/input/demo)
2. Change theme (fotocasa for instance)
3. Scroll down to `Addon and Icon`
4. See defect

![Input field wrong](https://user-images.githubusercontent.com/23620759/136563735-61523a61-5e5c-459d-b261-7f9ae752cc4f.png)

**Expected look and feel**
![Input field right](https://user-images.githubusercontent.com/23620759/136563744-a04e9a52-cc16-4ec5-982e-7fcb9c500e1b.png)

**Comment by rohit-raje-786** [comment]
@turolopezsanabria can i work on this issue?

**Comment by turolopezsanabria** [comment]
sure! go ahead
thanks @rohit-raje-786 

> @turolopezsanabria can i work on this issue?

**Comment by harshndroid** [comment]
@turolopezsanabria i want to know is this issue solved or still open?

**Comment by andresin87** [comment]
still open

**Comment by harshndroid** [comment]
@andresin87 @turolopezsanabria plz check pull request #1858 . Thanks

**Comment by harshndroid** [comment]
@andresin87 is there something i need to check ?
