### ISSUE TITLE
Dev env not working

### ISSUE THREAD

**Issue by delalama** [SUI-Components/SUIComponents#1805]
npm run dev not working

How do you actually deploy dev env?

**Steps to reproduce**
1. Run   npm run dev

**Expected behaviour**
No error

**Actual behaviour**
../sui-components/node_modules/@s-ui/studio/bin/sui-studio-dev.js:38
const [category, component] = componentID.split('/')
                                          ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/home/elaltas/devel/hacktoberfest/sui-components/node_modules/@s-ui/studio/bin/sui-studio-dev.js:38:43)

**Environment / Context**
node -> 16.5.0
npm -> 7.14
ubuntu 20.04

**Comment by andresin87** [comment]
you should use `npm run dev [category/component]` to run an specific component

**Comment by delalama** [comment]
thanks andres
