### ISSUE TITLE
AtomSlider handler throws an error after AtomUpload dependency updating

### ISSUE THREAD

**Issue by AitorRodriguez990** [SUI-Components/SUIComponents#1974]
**Describe the bug**

After updating the `AtomUpload` dependency it throws an error on combining it with the `AtomSlider` component.

This is the Pull Request where dependency was updated: https://github.com/SUI-Components/sui-components/pull/1959/files#diff-4e1f649388c3a56b144d802e3cc6f4cec5094ed6538bffa8f11a0a7235c8c89cL14

**Steps to reproduce**

Use `AtomUpload` component in combination with the `AtomSlider` component.

**Expected behaviour**

The image needs to be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/13108014/151523908-d9d012ab-fff7-4c5e-9b9f-b959fdfdbaf3.png)

**Environment / Context**
- Desktop or Mobile? Desktop/Mobile
- Operating System: macOS
- Browser and version Chrome 97
- Device: MacBook Pro

**Additional info**

Thank you!

**Comment by andresin87** [comment]
Handler needs to be Client-side-rendered
