### ISSUE TITLE
Non-text inputs don't get focus in tab navigation

### ISSUE THREAD

**Issue by beatrizip** [SUI-Components/SUIComponents#2023]
**Describe the bug**
non-text inputs don't get focus in tab navigation

**Steps to reproduce**
1. Go to [input demo](https://sui-components.vercel.app/workbench/atom/input/demo)
2. Click on any input
4. Try to do tab focus for all inputs

**Comment by andresin87** [comment]
maybe is due to the `tabindex="-1"` default prop, in my opinion
