### ISSUE TITLE
AtomUpload react-DropZone is not currently providing on its handler the preview

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2056]
**Describe the bug**
During the dependencies update, the photoUploader upgrades its DropZone dependency from v5 to v11. It suposes a tackled refactor but we forgot to test one feature which was provided in v5 by default but the current version does not.

[react-dropzone-section-previews](https://react-dropzone.js.org/#section-previews)
```
Starting with version 7.0.0, the {preview} property generation on the [File](https://developer.mozilla.org/en-US/docs/Web/API/File) objects and the {disablePreview} property on the <Dropzone> have been removed.

If you need need the {preview}, it can be easily achieved in the onDrop() callback:
````

**Expected behaviour**
The callback might provide the preview blob:
```js
file => Object.assign(file, {
  preview: URL.createObjectURL(file)
})
```

**Comment by andresin87** [comment]
@xaviermariaconejo

**Comment by xaviermariaconejo** [comment]
good job! :D
