### ISSUE TITLE
🪲 label and nodeLabel do not trigger onChange status when using a custom checkedIcon prop

### ISSUE THREAD

**Issue by alfdocimo** [SUI-Components/SUIComponents#2289]
### URL

https://sui-components.vercel.app/workbench/molecule/checkboxField/documentation/api

### Steps to reproduce

1. Create a CheckboxField component
2. set the checkedIcon prop to be a custom Icon (CheckboxCheckedIcon for instance)
3. Click on the label to mark the checkbox as checked, and click the label again to uncheck it

### Expected Behavior

The label should work as it does by default with a custom checkbox icon

Example:

https://codesandbox.io/s/modest-leftpad-og48ix?file=/src/App.js

### Which device have you used?

- [X] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] smartTV

### Which operating systems have you used?

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by xmurcia** [comment]
Hi! @andresin87 , can I take this one?

**Comment by andresin87** [comment]
of course!
