### ISSUE TITLE
✨ AtomTooltip replace the TooltipExtendChildren ref code by the useMergeRefs hook

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2318]
### Describe the solution you'd like

repplace the ref merging function by the `@s-ui/react-hooks/lib/useMergeRefs`

**Comment by VarunGitGood** [comment]
can i work on this

**Comment by andresin87** [comment]
of course!

**Comment by andresin87** [comment]
install the `"@s-ui/react-hooks": 1` to the `component/atom/tooltip/package.json `dependencies
