### ISSUE TITLE
✨Replace AtomPopover cloneElement by PrimitiveInjector

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2328]
### Describe the solution you'd like

In the PopoverExtendChildren class
Wrap the TooltipExtendChildren children in an @s-ui/primitiveInjector with the proper props: onClick and className and also the ref

### Additional info

take a look on #2317

**Comment by meerhamzadev** [comment]
Hey, I'm interested in this issue. Can you explain this issue a little more? and also can you spot the file where we are supposed to do refactor.

**Comment by andresin87** [comment]
@meerhamzadev sorry. maybe #2403 is an easier one.
