### ISSUE TITLE
✨Avatar cloneElement replacement by Injector

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2332]
### Describe the solution you'd like

replace the 
```js
const children = Children.toArray(childrenProp)
      .filter(child => isValidElement(child))
      .map(child => cloneElement(child, {size}))
```

found in `components/atom/avatar/src/index`by the proper usage of `PrimitiveInjector`

```js
<Injector size={size}>
  {children}
</Injector>
```

**Comment by stefi23** [comment]
@andresin87 There was no `components/atom/avatar/` and by looking through the component I found the `components/molecule/avatar` and replaced it there.

**Comment by oegea** [comment]
Seems that this issue was duplicated and we made same changes on different PRs 😅 @stefi23 @andresin87

**Comment by stefi23** [comment]
Thanks for the heads up @oegea. I didn't realize that 🙈 If you already updated the component maybe this issue can be closed.

**Comment by andresin87** [comment]
sorry, I'll add tomorrow a lot of new easy issues for testing helping all of us to increase coverage.
Remember Testing means commitment against users and its aligned with @hacktoberfest' 2/3 values
- QUANTITY IS FUN, QUALITY IS KEY
- SHORT-TERM ACTION, LONG-TERM IMPACT
