### ISSUE TITLE
✨field refactor

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2334]
### Describe the solution you'd like

in `components/molecule/field/src/Label`
the...
```js
// innerLabel fn
if(label) {
	if(isElement(label) ) {
		// return case A**
    } else {
		// this is different
	}
} else if(nodeLabel) {
	// retrun case B**
}
// return null
````
... return case A and B are equal. Simplify that conditional clausules to join both cases and remove the ternary

**Comment by sephoenix** [comment]
Can I take it?

**Comment by andresin87** [comment]
Yeah!
