### ISSUE TITLE
✨radioButtonGroup cloneElement replacement by Injector

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2336]
### Describe the solution you'd like

in `components/molecule/radioButtonGroup` there is a children loop `extendedChildren` wich clone each child by adding checked prop and a handler. Replace it by an injector

**Comment by Xaconi** [comment]
Hi there, can I get this one?

**Comment by andresin87** [comment]
Of course

**Comment by andresin87** [comment]
you will probably need to install `@s-ui/react-primitive-injector`in `components/molecule/radioButotnGroup` directory

take care the package.json inly targets the v1:

```json
{
    ...
    "dependencies": {
        ...
        "@s-ui/react-primitive-injector": "1",
        ...
    }
    ...
}
```

**Comment by andresin87** [comment]
take a look on https://github.com/SUI-Components/sui-components/pull/2348 as an example
