### ISSUE TITLE
✨MoleculeDropdownOption mispelling error

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2371]
### Describe the solution you'd like

https://github.com/SUI-Components/sui-components/blob/master/components/molecule/dropdownOption/src/index.js#L167

misspelling error

**Comment by andresin87** [comment]
@sephoenix could you assign it to you?

**Comment by andresin87** [comment]
`Addtional`to `Additional `

**Comment by sephoenix** [comment]
> @sephoenix could you assign it to you?

Sure!
