### ISSUE TITLE
✨ Component Accordion: The arrows are upside down

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#2374]
### Is your iteration request related to a problem?

The arrows are upside down.

### Describe the solution you'd like

They should point down when collapsed and up whenever the items are expanded.

### Screenshots

![221004 - Accordion icons](https://user-images.githubusercontent.com/23620759/193868664-cebbbf45-13d0-4055-a1db-3116670b9719.png)

**Comment by najeebkp** [comment]
hi @turolopezsanabria please assign this to me

**Comment by joanjeremiah** [comment]
I would like to solve this issue. Kindly assign this task to me.

**Comment by abhishekpatil4** [comment]
@turolopezsanabria Assign me this task, will get it done in no time

**Comment by andresin87** [comment]
talk with you all to determine who are gonna take it.

The icon is made with css :before and :after technique it its :empty

and using the transform rotate technique

**Comment by najeebkp** [comment]
@andresin87  im not able to run in my local. anything other than npm install is needed? pleas help me

**Comment by andresin87** [comment]
npm run respawn
npm run dev molecule/accordion
