### ISSUE TITLE
🎨 Remove the section UX Specs from all demos - Delete at SUI Studio level

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#2376]
### Acceptance Criteria

Remove the section UX Specs from all demos - Delete at SUI Studio level

![221004 - Remove UX Specs section](https://user-images.githubusercontent.com/23620759/193871108-f8c8c0fe-dd3a-49cd-877f-5b3c7181468d.png)

### Definition of done (DOD)

- The tab UX Specs is no longer visible in the demo
- The code of UX Specs code is no longer available in SUI Studio (remove from code)
- All UX Specs are removed from each component.

### Additional info

All the UX specs are stored in Lingo and Figma now.
All the relevant information for SUI Demos should be included as part of the demos and the readme section when relevant.

**Comment by corners2wall** [comment]
Pls, assign this issue to me

**Comment by shafi9155** [comment]
@turolopezsanabria Assign this issue to me

**Comment by andresin87** [comment]
The right project is [sui-studio](https://github.com/SUI-Components/sui/tree/master/packages/sui-studio).

The requirements are
- do not copy the UXDEf file https://github.com/SUI-Components/sui/blob/5e84eef9c89a9066dc3a5237fd1556db5a4eafc7/packages/sui-studio/bin/helpers/copyStaticFiles.js#L13
- remove the showUX state, useEffect and jsx render https://github.com/SUI-Components/sui/blob/6fff53d64ac0e8ac41e690ff829ca2f82500a65f/packages/sui-studio/src/components/workbench/index.js
- remove the route: https://github.com/SUI-Components/sui/blob/2d39df4c0e49490ff29f2887bd10a55e74b2c548/packages/sui-studio/src/routes.js#L35
- rmeove the constant: https://github.com/SUI-Components/sui/blob/7f92cf4d339b316cc54901e003d23a9b8c9d4344/packages/sui-studio/src/constants.js#L4

This will reduce the number of files to deploy and also will make studio perform better.
@arnau-rius @rmoralp I'm forgetting something else?
