### ISSUE TITLE
🎨 Demo Panel - all thumbnails should be 100px squares

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#2380]
### Acceptance Criteria

All items of the demo should be 100px * 100px

![Captura de Pantalla 2022-10-04 a las 18 46 57](https://user-images.githubusercontent.com/23620759/193879159-ed07dbd7-99d2-4f92-b44d-0bba5520bb8e.png)

### Definition of done (DOD)

All items of the demo should be 100px * 100px

### Additional info

This is how it looks right now:
![221004 - super big panels](https://user-images.githubusercontent.com/23620759/193879029-7075fa54-dc6c-44f8-9373-8d16a68bee89.png)

**Comment by Pnukso** [comment]
I'll take this

**Comment by andresin87** [comment]
@Pnukso are you gonna take it?

**Comment by oriolpuig** [comment]
I'll take that one.
