### ISSUE TITLE
✨Molecule/Accordion icon transition

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2392]
### Is your iteration request related to a problem?

When a panel is open-closed the icon rotates pointing to the outside of the panel.

### Describe the solution you'd like

It must be rotating onside

### Additional context
the issue https://github.com/SUI-Components/sui-components/issues/2392 generate this request

**Comment by andresin87** [comment]
This must be ralated to:
https://github.com/SUI-Components/sui-components/blob/master/components/molecule/accordion/src/styles/index.scss#L151
https://github.com/SUI-Components/sui-components/blob/master/components/molecule/accordion/src/styles/index.scss#L155
and 
https://github.com/SUI-Components/sui-components/blob/master/components/molecule/accordion/src/styles/index.scss#L160

**Comment by andresin87** [comment]
maybe @najeebkp can be the right person to take that. Do you want to get enroled on that?

**Comment by najeebkp** [comment]
sure @andresin87 please assign this to me. I'll take care!
