### ISSUE TITLE
✨ Remove images only needed for Readme

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/SUIComponents#2402]
### Is your iteration request related to a problem?

There are a few components including an image in the readme section.

❌ These images are hard to maintain, we can not ensure they are up to date (they are not)
❌ These images are not "painted" on the Studio readme section either, just on the GitHub page
❌ The use of it is not consistent, there are just a few components with this type of irrelevant information nowadays

### Describe the solution you'd like

- Remove the images from the documentation
- Remove the assets folder from those components that have one
- Check the .npmignore files, the assets folder is there for some components

### Screenshots

<img width="426" alt="remove assets from  npmignore" src="https://user-images.githubusercontent.com/23620759/196000593-916e6ea2-d3b3-49b2-a331-512953e6062f.png">

![remove assets 1](https://user-images.githubusercontent.com/23620759/196000601-864f1d65-d570-45ab-bc53-633c40d88eb9.png)

![remove assets 2](https://user-images.githubusercontent.com/23620759/196000602-e48ed0c6-701f-4e02-973d-02352fd303d8.png)

**Comment by tes-balo** [comment]
Can I approach this?

**Comment by andresin87** [comment]
yup 👍
