### ISSUE TITLE
🎨 Molecule/Avatar fallbackColor Demo

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2403]
### Acceptance Criteria

The Avatar demo should include a proper way to demonstrate how the user can get The avatar and define a color or leave it undefined and get a random one

### Definition of done (DOD)

- [x] Add a demo article called `ArticleFallbackColor`
- [x] Include a descriptive article as other does with:
  - [x] Input for name
  - [x] Input for fallbackColor Prop
  - [x] Result
- [x] Add description of the desired behavior

**Comment by oriolpuig** [comment]
I've kept the demo at `ArticleImage` instead of create a new demo article, because this demo is related with Image example as de fallback name is.
