### ISSUE TITLE
✨molecule select-popover useEffect has as missing dependency

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2404]
### Is your iteration request related to a problem?

React Hook useEffect has a missing dependency: 'placement'. Either include it or remove the dependency array (react-hooks/exhaustive-deps)

/components/molecule/selectPopover/src/index.js

### Describe the solution you'd like

add `placement`to the propeer useEffect

**Comment by rparthas** [comment]
I am interested to work on it. Shall I pick it up ?

**Comment by andresin87** [comment]
Of course yes. Ill make some other similar now
