### ISSUE TITLE
🎨  React Hook useCallback has an unnecessary dependency

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/SUIComponents#2408]
### Acceptance Criteria

/components/hook/usePortal/demo/articles/ArticleCustom/useTooltip.js

useCallback has an unnecessary dependency:
`isOpened`

### Definition of done (DOD)

- [ ] remove it

**Comment by tes-balo** [comment]
can I work on this?

**Comment by andresin87** [comment]
Yes

**Comment by tes-balo** [comment]
I have removed the dependency. However, I am having trouble pushing the changes to my fork. The pre-push is always failing.

![Screenshot from 2022-10-22 18-48-31](https://user-images.githubusercontent.com/72257135/197355652-6d7dbb26-da56-4ecb-b8d7-f262dd180171.png)
![Screenshot from 2022-10-22 18-48-27](https://user-images.githubusercontent.com/72257135/197355692-d505f132-e170-45a6-9f71-0385b85d14b0.png)

**Comment by andresin87** [comment]
Npm run respawn

**Comment by andresin87** [comment]
Npm run test
